{% set name = "jekyll" %}
{% set version = "3.8.5" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 6316459a4524a971e2553f794d2e3ec66f4341ca8452153df855500406d3c2da

build:
  noarch: generic
  number: 0
  script: 
    - gem install --norc -N -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-addressable >=2.4,<3
    - rb-colorator >=1.0,<2
    - rb-em-websocket >=0.5,<1
    - rb-i18n >=0.7,<1
    - rb-jekyll-sass-converter >=1.0,<2
    - rb-jekyll-watch >=2,<3
    - rb-kramdown >=1.14,<2
    - rb-liquid >=4.0,<5
    - rb-mercenary >=0.3.3,<0.4
    - rb-pathutil >=0.9,<1
    - rb-rouge >=1.7,<4
    - rb-safe_yaml >=1.0,<2

test:
  requires:
    - git
  commands:
    - jekyll --help
    - jekyll build --help
    - jekyll clean --help
    - jekyll hyde --help
    - jekyll new-theme test-theme
    - jekyll serve --help
    # Import tests
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Jekyll is a simple, blog aware, static site generator 

  description: |
    Jekyll is a simple, extendable, static site generator. You give it text
    written in your favorite markup language and it churns through layouts to
    create a static website. Throughout that process you can tweak how you
    want the site URLs to look, what data gets displayed in the layout, and
    more.  
  doc_url: https://jekyllrb.com/docs
  dev_url: http://github.com/jekyll/{{ name }}

extra:
  recipe-maintainers:
    - sodre
