travis:
  secure:
    BINSTAR_TOKEN: Mi0WzyuI1bNcUguVtK67MUXbcuo0BRdC00bBCkdOfy6enCjJnqzo8rhjcUgL2F9WP/AZLz2Jwv6f9Ve4+hqI79nCuFjVPPSlP04uJKDJsNBbFDgCVM7vthWKRUiQDZWL7LIUX0NCR7klP6xFU0FwMDz8nrQMKs0nC7ZAVNSr7ChXWHCUS8o2QyaYCQgCR91XubAx1ZjIcYrZy5o3eGwUFjWJpExVrN2QkSFq0JVGV0PMyl1FF3i3RYnUEOgWJq9Js4y6FwQmoYypWwAm07btHo7MCISdzwQTDN90tC8nRzcdPa3eJhh1PTD4amcuHI/yGs456vSpNqBn4w39jknECCwsfmJQEaRkiw/q99JQbql8GgDa58TYmPuGFl/NXx+03Dta8keRoqA8l+8T+2FzbAF4FQWCUsNhy16v2UehK5Ll4diiXyru30Rw5sb87mg2i2/ZNHnuyNKJwbwYeRLmf1UkBbeG2CMCcbunjOBT6jUDmqq5JPvy5V9yPpqcvG0957Z/vtJwKgQxUIQxok+A/6Acx5PHG3LGm75pS7/01Xw5vAGhgJBdCjNjS1L7xPaqrTZt0G5xBEEPaYG0S+axY17NKDOjuj76xb8moa3b1WANlAIy/gKdspVB+/oEDwQ9eLDrHIOyY42qt4ZluM4B63xUowfQv4Yk7OO2PWIpJm4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
